[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
    "python3.12 -m venv /app/.venv",
    "/app/.venv/bin/pip install -r requirements.txt",
    "ln -sf /app/.venv/bin/alembic /usr/local/bin/alembic",
    "ln -sf /app/.venv/bin/uvicorn /usr/local/bin/uvicorn",
    "ln -sf /app/.venv/bin/python3.12 /usr/local/bin/python3.12"
]

[phases.build]
cmds = []

[start]
cmd = "export PYTHONPATH=/app && /app/.venv/bin/alembic upgrade head && /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
